<?
$adWordsTargetingList=Array(

'countries'=>Array(
Array("id"=>"*","text"=>"All Countries and Territories"),
Array("id"=>"","text"=>"------"),
Array("id"=>"AU","text"=>"Australia"),
Array("id"=>"AT","text"=>"Austria"),
Array("id"=>"BE","text"=>"Belgium"),
Array("id"=>"BR","text"=>"Brazil"),
Array("id"=>"CA","text"=>"Canada"),
Array("id"=>"CN","text"=>"China"),
Array("id"=>"DK","text"=>"Denmark"),
Array("id"=>"FI","text"=>"Finland"),
Array("id"=>"FR","text"=>"France"),
Array("id"=>"DE","text"=>"Germany"),
Array("id"=>"HK","text"=>"Hong Kong"),
Array("id"=>"IT","text"=>"Italy"),
Array("id"=>"JP","text"=>"Japan"),
Array("id"=>"NL","text"=>"Netherlands"),
Array("id"=>"NO","text"=>"Norway"),
Array("id"=>"PT","text"=>"Portugal"),
Array("id"=>"SG","text"=>"Singapore"),
Array("id"=>"KR","text"=>"South Korea"),
Array("id"=>"ES","text"=>"Spain"),
Array("id"=>"SE","text"=>"Sweden"),
Array("id"=>"CH","text"=>"Switzerland"),
Array("id"=>"TW","text"=>"Taiwan"),
Array("id"=>"GB","text"=>"United Kingdom"),
Array("id"=>"US","text"=>"United States"),
Array("id"=>"","text"=>"------"),
Array("id"=>"AF","text"=>"Afghanistan"),
Array("id"=>"AL","text"=>"Albania"),
Array("id"=>"DZ","text"=>"Algeria"),
Array("id"=>"AS","text"=>"American Samoa"),
Array("id"=>"AD","text"=>"Andorra"),
Array("id"=>"AO","text"=>"Angola"),
Array("id"=>"AI","text"=>"Anguilla"),
Array("id"=>"AQ","text"=>"Antarctica"),
Array("id"=>"AG","text"=>"Antigua and Barbuda"),
Array("id"=>"AR","text"=>"Argentina"),
Array("id"=>"AM","text"=>"Armenia"),
Array("id"=>"AW","text"=>"Aruba"),
Array("id"=>"AU","text"=>"Australia"),
Array("id"=>"AT","text"=>"Austria"),
Array("id"=>"AZ","text"=>"Azerbaijan"),
Array("id"=>"BS","text"=>"Bahamas"),
Array("id"=>"BH","text"=>"Bahrain"),
Array("id"=>"BD","text"=>"Bangladesh"),
Array("id"=>"BB","text"=>"Barbados"),
Array("id"=>"BY","text"=>"Belarus"),
Array("id"=>"BE","text"=>"Belgium"),
Array("id"=>"BZ","text"=>"Belize"),
Array("id"=>"BJ","text"=>"Benin"),
Array("id"=>"BM","text"=>"Bermuda"),
Array("id"=>"BT","text"=>"Bhutan"),
Array("id"=>"BO","text"=>"Bolivia"),
Array("id"=>"BA","text"=>"Bosnia and Herzegovina"),
Array("id"=>"BW","text"=>"Botswana"),
Array("id"=>"BV","text"=>"Bouvet Island"),
Array("id"=>"BR","text"=>"Brazil"),
Array("id"=>"IO","text"=>"British Indian Ocean Territory"),
Array("id"=>"BN","text"=>"Brunei Darussalam"),
Array("id"=>"BG","text"=>"Bulgaria"),
Array("id"=>"BF","text"=>"Burkina Faso"),
Array("id"=>"BI","text"=>"Burundi"),
Array("id"=>"KH","text"=>"Cambodia"),
Array("id"=>"CM","text"=>"Cameroon"),
Array("id"=>"CA","text"=>"Canada"),
Array("id"=>"CV","text"=>"Cape Verde"),
Array("id"=>"KY","text"=>"Cayman Islands"),
Array("id"=>"CF","text"=>"Central African Republic"),
Array("id"=>"TD","text"=>"Chad"),
Array("id"=>"CL","text"=>"Chile"),
Array("id"=>"CN","text"=>"China"),
Array("id"=>"CX","text"=>"Christmas Island"),
Array("id"=>"CC","text"=>"Cocos (Keeling) Islands"),
Array("id"=>"CO","text"=>"Colombia"),
Array("id"=>"KM","text"=>"Comoros"),
Array("id"=>"CG","text"=>"Congo"),
Array("id"=>"CD","text"=>"Congo, Democratic Republic"),
Array("id"=>"CK","text"=>"Cook Islands"),
Array("id"=>"CR","text"=>"Costa Rica"),
Array("id"=>"CI","text"=>"Cote d'Ivoire"),
Array("id"=>"HR","text"=>"Croatia"),
Array("id"=>"CU","text"=>"Cuba"),
Array("id"=>"CY","text"=>"Cyprus"),
Array("id"=>"CZ","text"=>"Czech Republic"),
Array("id"=>"DK","text"=>"Denmark"),
Array("id"=>"DJ","text"=>"Djibouti"),
Array("id"=>"DM","text"=>"Dominica"),
Array("id"=>"DO","text"=>"Dominican Republic"),
Array("id"=>"TL","text"=>"East Timor"),
Array("id"=>"EC","text"=>"Ecuador"),
Array("id"=>"EG","text"=>"Egypt"),
Array("id"=>"SV","text"=>"El Salvador"),
Array("id"=>"GQ","text"=>"Equatorial Guinea"),
Array("id"=>"ER","text"=>"Eritrea"),
Array("id"=>"EE","text"=>"Estonia"),
Array("id"=>"ET","text"=>"Ethiopia"),
Array("id"=>"FK","text"=>"Falkland Islands (Malvinas)"),
Array("id"=>"FO","text"=>"Faroe Islands"),
Array("id"=>"FJ","text"=>"Fiji"),
Array("id"=>"FI","text"=>"Finland"),
Array("id"=>"FR","text"=>"France"),
Array("id"=>"GF","text"=>"French Guiana"),
Array("id"=>"PF","text"=>"French Polynesia"),
Array("id"=>"TF","text"=>"French Southern Territories"),
Array("id"=>"GA","text"=>"Gabon"),
Array("id"=>"GM","text"=>"Gambia"),
Array("id"=>"GE","text"=>"Georgia"),
Array("id"=>"DE","text"=>"Germany"),
Array("id"=>"GH","text"=>"Ghana"),
Array("id"=>"GI","text"=>"Gibraltar"),
Array("id"=>"GR","text"=>"Greece"),
Array("id"=>"GL","text"=>"Greenland"),
Array("id"=>"GD","text"=>"Grenada"),
Array("id"=>"GP","text"=>"Guadeloupe"),
Array("id"=>"GU","text"=>"Guam"),
Array("id"=>"GT","text"=>"Guatemala"),
Array("id"=>"GN","text"=>"Guinea"),
Array("id"=>"GW","text"=>"Guinea-Bissau"),
Array("id"=>"GY","text"=>"Guyana"),
Array("id"=>"HT","text"=>"Haiti"),
Array("id"=>"HM","text"=>"Heard and McDonald Islands"),
Array("id"=>"HN","text"=>"Honduras"),
Array("id"=>"HK","text"=>"Hong Kong"),
Array("id"=>"HU","text"=>"Hungary"),
Array("id"=>"IS","text"=>"Iceland"),
Array("id"=>"IN","text"=>"India"),
Array("id"=>"ID","text"=>"Indonesia"),
Array("id"=>"IR","text"=>"Iran"),
Array("id"=>"IQ","text"=>"Iraq"),
Array("id"=>"IE","text"=>"Ireland"),
Array("id"=>"IL","text"=>"Israel"),
Array("id"=>"IT","text"=>"Italy"),
Array("id"=>"JM","text"=>"Jamaica"),
Array("id"=>"JP","text"=>"Japan"),
Array("id"=>"JO","text"=>"Jordan"),
Array("id"=>"KZ","text"=>"Kazakhstan"),
Array("id"=>"KE","text"=>"Kenya"),
Array("id"=>"KI","text"=>"Kiribati"),
Array("id"=>"KW","text"=>"Kuwait"),
Array("id"=>"KG","text"=>"Kyrgyzstan"),
Array("id"=>"LA","text"=>"Lao People's Democratic Republic"),
Array("id"=>"LV","text"=>"Latvia"),
Array("id"=>"LB","text"=>"Lebanon"),
Array("id"=>"LS","text"=>"Lesotho"),
Array("id"=>"LR","text"=>"Liberia"),
Array("id"=>"LY","text"=>"Libya"),
Array("id"=>"LI","text"=>"Liechtenstein"),
Array("id"=>"LT","text"=>"Lithuania"),
Array("id"=>"LU","text"=>"Luxembourg"),
Array("id"=>"MO","text"=>"Macau"),
Array("id"=>"MK","text"=>"Macedonia"),
Array("id"=>"MG","text"=>"Madagascar"),
Array("id"=>"MW","text"=>"Malawi"),
Array("id"=>"MY","text"=>"Malaysia"),
Array("id"=>"MV","text"=>"Maldives"),
Array("id"=>"ML","text"=>"Mali"),
Array("id"=>"MT","text"=>"Malta"),
Array("id"=>"MH","text"=>"Marshall Islands"),
Array("id"=>"MQ","text"=>"Martinique"),
Array("id"=>"MR","text"=>"Mauritania"),
Array("id"=>"MU","text"=>"Mauritius"),
Array("id"=>"YT","text"=>"Mayotte"),
Array("id"=>"MX","text"=>"Mexico"),
Array("id"=>"FM","text"=>"Micronesia"),
Array("id"=>"MD","text"=>"Moldova"),
Array("id"=>"MC","text"=>"Monaco"),
Array("id"=>"MN","text"=>"Mongolia"),
Array("id"=>"MS","text"=>"Montserrat"),
Array("id"=>"MA","text"=>"Morocco"),
Array("id"=>"MZ","text"=>"Mozambique"),
Array("id"=>"MM","text"=>"Myanmar"),
Array("id"=>"NA","text"=>"Namibia"),
Array("id"=>"NR","text"=>"Nauru"),
Array("id"=>"NP","text"=>"Nepal"),
Array("id"=>"NL","text"=>"Netherlands"),
Array("id"=>"AN","text"=>"Netherlands Antilles"),
Array("id"=>"NC","text"=>"New Caledonia"),
Array("id"=>"NZ","text"=>"New Zealand"),
Array("id"=>"NI","text"=>"Nicaragua"),
Array("id"=>"NE","text"=>"Niger"),
Array("id"=>"NG","text"=>"Nigeria"),
Array("id"=>"NU","text"=>"Niue"),
Array("id"=>"NF","text"=>"Norfolk Island"),
Array("id"=>"MP","text"=>"Northern Mariana Islands"),
Array("id"=>"KP","text"=>"North Korea"),
Array("id"=>"NO","text"=>"Norway"),
Array("id"=>"OM","text"=>"Oman"),
Array("id"=>"PK","text"=>"Pakistan"),
Array("id"=>"PW","text"=>"Palau"),
Array("id"=>"PS","text"=>"Palestinian Territory"),
Array("id"=>"PA","text"=>"Panama"),
Array("id"=>"PG","text"=>"Papua New Guinea"),
Array("id"=>"PY","text"=>"Paraguay"),
Array("id"=>"PE","text"=>"Peru"),
Array("id"=>"PH","text"=>"Philippines"),
Array("id"=>"PN","text"=>"Pitcairn"),
Array("id"=>"PL","text"=>"Poland"),
Array("id"=>"PT","text"=>"Portugal"),
Array("id"=>"PR","text"=>"Puerto Rico"),
Array("id"=>"QA","text"=>"Qatar"),
Array("id"=>"RE","text"=>"Reunion"),
Array("id"=>"RO","text"=>"Romania"),
Array("id"=>"RU","text"=>"Russian Federation"),
Array("id"=>"RW","text"=>"Rwanda"),
Array("id"=>"KN","text"=>"Saint Kitts and Nevis"),
Array("id"=>"LC","text"=>"Saint Lucia"),
Array("id"=>"VC","text"=>"Saint Vincent and the Grenadines"),
Array("id"=>"WS","text"=>"Samoa"),
Array("id"=>"SM","text"=>"San Marino"),
Array("id"=>"ST","text"=>"Sao Tome and Principe"),
Array("id"=>"SA","text"=>"Saudi Arabia"),
Array("id"=>"SN","text"=>"Senegal"),
Array("id"=>"CS","text"=>"Serbia and Montenegro"),
Array("id"=>"SC","text"=>"Seychelles"),
Array("id"=>"SL","text"=>"Sierra Leone"),
Array("id"=>"SG","text"=>"Singapore"),
Array("id"=>"SK","text"=>"Slovakia"),
Array("id"=>"SI","text"=>"Slovenia"),
Array("id"=>"SB","text"=>"Solomon Islands"),
Array("id"=>"SO","text"=>"Somalia"),
Array("id"=>"ZA","text"=>"South Africa"),
Array("id"=>"GS","text"=>"South Georgia and The South Sandwich Islands"),
Array("id"=>"KR","text"=>"South Korea"),
Array("id"=>"ES","text"=>"Spain"),
Array("id"=>"LK","text"=>"Sri Lanka"),
Array("id"=>"SH","text"=>"St. Helena"),
Array("id"=>"PM","text"=>"St. Pierre and Miquelon"),
Array("id"=>"SD","text"=>"Sudan"),
Array("id"=>"SR","text"=>"Suriname"),
Array("id"=>"SJ","text"=>"Svalbard and Jan Mayen Islands"),
Array("id"=>"SZ","text"=>"Swaziland"),
Array("id"=>"SE","text"=>"Sweden"),
Array("id"=>"CH","text"=>"Switzerland"),
Array("id"=>"SY","text"=>"Syria"),
Array("id"=>"TW","text"=>"Taiwan"),
Array("id"=>"TJ","text"=>"Tajikistan"),
Array("id"=>"TZ","text"=>"Tanzania"),
Array("id"=>"TH","text"=>"Thailand"),
Array("id"=>"TG","text"=>"Togo"),
Array("id"=>"TK","text"=>"Tokelau"),
Array("id"=>"TO","text"=>"Tonga"),
Array("id"=>"TT","text"=>"Trinidad and Tobago"),
Array("id"=>"TN","text"=>"Tunisia"),
Array("id"=>"TR","text"=>"Turkey"),
Array("id"=>"TM","text"=>"Turkmenistan"),
Array("id"=>"TC","text"=>"Turks and Caicos Islands"),
Array("id"=>"TV","text"=>"Tuvalu"),
Array("id"=>"UG","text"=>"Uganda"),
Array("id"=>"UA","text"=>"Ukraine"),
Array("id"=>"AE","text"=>"United Arab Emirates"),
Array("id"=>"GB","text"=>"United Kingdom"),
Array("id"=>"US","text"=>"United States"),
Array("id"=>"UM","text"=>"United States Minor Outlying Islands"),
Array("id"=>"UY","text"=>"Uruguay"),
Array("id"=>"UZ","text"=>"Uzbekistan"),
Array("id"=>"VU","text"=>"Vanuatu"),
Array("id"=>"VA","text"=>"Vatican"),
Array("id"=>"VE","text"=>"Venezuela"),
Array("id"=>"VN","text"=>"Viet Nam"),
Array("id"=>"VG","text"=>"Virgin Islands (British)"),
Array("id"=>"VI","text"=>"Virgin Islands (U.S.)"),
Array("id"=>"WF","text"=>"Wallis and Futuna Islands"),
Array("id"=>"EH","text"=>"Western Sahara"),
Array("id"=>"YE","text"=>"Yemen"),
Array("id"=>"ZM","text"=>"Zambia"),
Array("id"=>"ZW","text"=>"Zimbabwe"),
Array("id"=>"AU","text"=>"Australia")),

'regions'=>Array(
'US'=>Array(
Array("id"=>"US-AL","text"=>"Alabama AL"),
Array("id"=>"M:630","text"=>"---Birmingham AL"),
Array("id"=>"M:606","text"=>"---Dothan AL"),
Array("id"=>"M:691","text"=>"---Huntsville-Decatur (Florence) AL"),
Array("id"=>"M:686","text"=>"---Mobile AL-Pensacola (Ft. Walton Beach) FL"),
Array("id"=>"M:698","text"=>"---Montgomery (Selma) AL"),
Array("id"=>"US-AK","text"=>"Alaska AK"),
Array("id"=>"M:743","text"=>"---Anchorage AK"),
Array("id"=>"M:745","text"=>"---Fairbanks AK"),
Array("id"=>"M:747","text"=>"---Juneau AK"),
Array("id"=>"US-AZ","text"=>"Arizona AZ"),
Array("id"=>"M:753","text"=>"---Phoenix AZ"),
Array("id"=>"M:789","text"=>"---Tucson (Sierra Vista) AZ"),
Array("id"=>"M:771","text"=>"---Yuma AZ-El Centro CA"),
Array("id"=>"US-AR","text"=>"Arkansas AR"),
Array("id"=>"M:670","text"=>"---Ft. Smith-Fayetteville-Springdale-Rogers AR"),
Array("id"=>"M:734","text"=>"---Jonesboro AR"),
Array("id"=>"M:693","text"=>"---Little Rock-Pine Bluff AR"),
Array("id"=>"M:628","text"=>"---Monroe LA-El Dorado AR"),
Array("id"=>"US-CA","text"=>"California CA"),
Array("id"=>"M:800","text"=>"---Bakersfield CA"),
Array("id"=>"M:868","text"=>"---Chico-Redding CA"),
Array("id"=>"M:802","text"=>"---Eureka CA"),
Array("id"=>"M:866","text"=>"---Fresno-Visalia CA"),
Array("id"=>"M:803","text"=>"---Los Angeles CA"),
Array("id"=>"M:828","text"=>"---Monterey-Salinas CA"),
Array("id"=>"M:804","text"=>"---Palm Springs CA"),
Array("id"=>"M:862","text"=>"---Sacramento-Stockton-Modesto CA"),
Array("id"=>"M:825","text"=>"---San Diego CA"),
Array("id"=>"M:807","text"=>"---San Francisco-Oakland-San Jose CA"),
Array("id"=>"M:855","text"=>"---Santa Barbara-Santa Maria-San Luis Obispo CA"),
Array("id"=>"M:771","text"=>"---Yuma AZ-El Centro CA"),
Array("id"=>"US-CO","text"=>"Colorado CO"),
Array("id"=>"M:752","text"=>"---Colorado Springs-Pueblo CO"),
Array("id"=>"M:751","text"=>"---Denver CO"),
Array("id"=>"M:773","text"=>"---Grand Junction-Montrose CO"),
Array("id"=>"US-CT","text"=>"Connecticut CT"),
Array("id"=>"M:533","text"=>"---Hartford &amp; New Haven CT"),
Array("id"=>"US-DE","text"=>"Delaware DE"),
Array("id"=>"US-DC","text"=>"District of Columbia DC"),
Array("id"=>"M:511","text"=>"---Washington DC (Hagerstown MD)"),
Array("id"=>"US-FL","text"=>"Florida FL"),
Array("id"=>"M:571","text"=>"---Ft. Myers-Naples FL"),
Array("id"=>"M:592","text"=>"---Gainesville FL"),
Array("id"=>"M:561","text"=>"---Jacksonville FL"),
Array("id"=>"M:528","text"=>"---Miami-Ft. Lauderdale FL"),
Array("id"=>"M:686","text"=>"---Mobile AL-Pensacola (Ft. Walton Beach) FL"),
Array("id"=>"M:534","text"=>"---Orlando-Daytona Beach-Melbourne FL"),
Array("id"=>"M:656","text"=>"---Panama City FL"),
Array("id"=>"M:530","text"=>"---Tallahassee FL-Thomasville GA"),
Array("id"=>"M:539","text"=>"---Tampa-St. Petersburg (Sarasota) FL"),
Array("id"=>"M:548","text"=>"---West Palm Beach-Ft. Pierce FL"),
Array("id"=>"US-GA","text"=>"Georgia GA"),
Array("id"=>"M:525","text"=>"---Albany GA"),
Array("id"=>"M:524","text"=>"---Atlanta GA"),
Array("id"=>"M:520","text"=>"---Augusta GA"),
Array("id"=>"M:522","text"=>"---Columbus GA"),
Array("id"=>"M:503","text"=>"---Macon GA"),
Array("id"=>"M:507","text"=>"---Savannah GA"),
Array("id"=>"M:530","text"=>"---Tallahassee FL-Thomasville GA"),
Array("id"=>"US-HI","text"=>"Hawaii HI"),
Array("id"=>"M:744","text"=>"---Honolulu HI"),
Array("id"=>"US-ID","text"=>"Idaho ID"),
Array("id"=>"M:757","text"=>"---Boise ID"),
Array("id"=>"M:758","text"=>"---Idaho Falls-Pocatello ID"),
Array("id"=>"M:760","text"=>"---Twin Falls ID"),
Array("id"=>"US-IL","text"=>"Illinois IL"),
Array("id"=>"M:648","text"=>"---Champaign &amp; Springfield-Decatur,IL"),
Array("id"=>"M:602","text"=>"---Chicago IL"),
Array("id"=>"M:682","text"=>"---Davenport IA-Rock Island-Moline IL"),
Array("id"=>"M:632","text"=>"---Paducah KY-Cape Girardeau MO-Harrisburg-Mount Vernon IL"),
Array("id"=>"M:675","text"=>"---Peoria-Bloomington IL"),
Array("id"=>"M:717","text"=>"---Quincy IL-Hannibal MO-Keokuk IA"),
Array("id"=>"M:610","text"=>"---Rockford IL"),
Array("id"=>"US-IN","text"=>"Indiana IN"),
Array("id"=>"M:649","text"=>"---Evansville IN"),
Array("id"=>"M:509","text"=>"---Ft. Wayne IN"),
Array("id"=>"M:527","text"=>"---Indianapolis IN"),
Array("id"=>"M:642","text"=>"---Lafayette IN"),
Array("id"=>"M:588","text"=>"---South Bend-Elkhart IN"),
Array("id"=>"M:581","text"=>"---Terre Haute IN"),
Array("id"=>"US-IA","text"=>"Iowa IA"),
Array("id"=>"M:637","text"=>"---Cedar Rapids-Waterloo-Iowa City &amp; Dubuque IA"),
Array("id"=>"M:682","text"=>"---Davenport IA-Rock Island-Moline IL"),
Array("id"=>"M:679","text"=>"---Des Moines-Ames IA"),
Array("id"=>"M:631","text"=>"---Ottumwa IA-Kirksville MO"),
Array("id"=>"M:717","text"=>"---Quincy IL-Hannibal MO-Keokuk IA"),
Array("id"=>"M:611","text"=>"---Rochester MN-Mason City IA-Austin MN"),
Array("id"=>"M:624","text"=>"---Sioux City IA"),
Array("id"=>"US-KS","text"=>"Kansas KS"),
Array("id"=>"M:603","text"=>"---Joplin MO-Pittsburg KS"),
Array("id"=>"M:605","text"=>"---Topeka KS"),
Array("id"=>"M:678","text"=>"---Wichita-Hutchinson KS"),
Array("id"=>"US-KY","text"=>"Kentucky KY"),
Array("id"=>"M:736","text"=>"---Bowling Green KY"),
Array("id"=>"M:541","text"=>"---Lexington KY"),
Array("id"=>"M:529","text"=>"---Louisville KY"),
Array("id"=>"M:632","text"=>"---Paducah KY-Cape Girardeau MO-Harrisburg-Mount Vernon IL"),
Array("id"=>"M:531","text"=>"---Tri-Cities TN-VA"),
Array("id"=>"US-LA","text"=>"Louisiana LA"),
Array("id"=>"M:644","text"=>"---Alexandria LA"),
Array("id"=>"M:716","text"=>"---Baton Rouge LA"),
Array("id"=>"M:582","text"=>"---Lafayette LA"),
Array("id"=>"M:643","text"=>"---Lake Charles LA"),
Array("id"=>"M:628","text"=>"---Monroe LA-El Dorado AR"),
Array("id"=>"M:622","text"=>"---New Orleans LA"),
Array("id"=>"M:612","text"=>"---Shreveport LA"),
Array("id"=>"US-ME","text"=>"Maine ME"),
Array("id"=>"M:537","text"=>"---Bangor ME"),
Array("id"=>"M:500","text"=>"---Portland-Auburn ME"),
Array("id"=>"M:552","text"=>"---Presque Isle ME"),
Array("id"=>"US-MD","text"=>"Maryland MD"),
Array("id"=>"M:512","text"=>"---Baltimore MD"),
Array("id"=>"M:576","text"=>"---Salisbury MD"),
Array("id"=>"M:511","text"=>"---Washington DC (Hagerstown MD)"),
Array("id"=>"US-MA","text"=>"Massachusetts MA"),
Array("id"=>"M:506","text"=>"---Boston MA-Manchester NH"),
Array("id"=>"M:521","text"=>"---Providence RI-New Bedford MA"),
Array("id"=>"M:543","text"=>"---Springfield-Holyoke MA"),
Array("id"=>"US-MI","text"=>"Michigan MI"),
Array("id"=>"M:583","text"=>"---Alpena MI"),
Array("id"=>"M:505","text"=>"---Detroit MI"),
Array("id"=>"M:513","text"=>"---Flint-Saginaw-Bay City MI"),
Array("id"=>"M:563","text"=>"---Grand Rapids-Kalamazoo-Battle Creek MI"),
Array("id"=>"M:551","text"=>"---Lansing MI"),
Array("id"=>"M:553","text"=>"---Marquette MI"),
Array("id"=>"M:540","text"=>"---Traverse City-Cadillac MI"),
Array("id"=>"US-MN","text"=>"Minnesota MN"),
Array("id"=>"M:676","text"=>"---Duluth MN-Superior WI"),
Array("id"=>"M:737","text"=>"---Mankato MN"),
Array("id"=>"M:613","text"=>"---Minneapolis-St. Paul MN"),
Array("id"=>"M:611","text"=>"---Rochester MN-Mason City IA-Austin MN"),
Array("id"=>"US-MS","text"=>"Mississippi MS"),
Array("id"=>"M:746","text"=>"---Biloxi-Gulfport MS"),
Array("id"=>"M:673","text"=>"---Columbus-Tupelo-West Point MS"),
Array("id"=>"M:647","text"=>"---Greenwood-Greenville MS"),
Array("id"=>"M:710","text"=>"---Hattiesburg-Laurel MS"),
Array("id"=>"M:639","text"=>"---Jackson MS"),
Array("id"=>"M:711","text"=>"---Meridian MS"),
Array("id"=>"US-MO","text"=>"Missouri MO"),
Array("id"=>"M:604","text"=>"---Columbia-Jefferson City MO"),
Array("id"=>"M:603","text"=>"---Joplin MO-Pittsburg KS"),
Array("id"=>"M:616","text"=>"---Kansas City MO"),
Array("id"=>"M:631","text"=>"---Ottumwa IA-Kirksville MO"),
Array("id"=>"M:632","text"=>"---Paducah KY-Cape Girardeau MO-Harrisburg-Mount Vernon IL"),
Array("id"=>"M:717","text"=>"---Quincy IL-Hannibal MO-Keokuk IA"),
Array("id"=>"M:619","text"=>"---Springfield MO"),
Array("id"=>"M:638","text"=>"---St. Joseph MO"),
Array("id"=>"M:609","text"=>"---St. Louis MO"),
Array("id"=>"US-MT","text"=>"Montana MT"),
Array("id"=>"M:756","text"=>"---Billings MT"),
Array("id"=>"M:754","text"=>"---Butte-Bozeman MT"),
Array("id"=>"M:798","text"=>"---Glendive MT"),
Array("id"=>"M:755","text"=>"---Great Falls MT"),
Array("id"=>"M:766","text"=>"---Helena MT"),
Array("id"=>"M:762","text"=>"---Missoula MT"),
Array("id"=>"US-NE","text"=>"Nebraska NE"),
Array("id"=>"M:759","text"=>"---Cheyenne WY-Scottsbluff NE"),
Array("id"=>"M:722","text"=>"---Lincoln &amp; Hastings-Kearney NE"),
Array("id"=>"M:740","text"=>"---North Platte NE"),
Array("id"=>"M:652","text"=>"---Omaha NE"),
Array("id"=>"US-NV","text"=>"Nevada NV"),
Array("id"=>"M:839","text"=>"---Las Vegas NV"),
Array("id"=>"M:811","text"=>"---Reno NV"),
Array("id"=>"US-NH","text"=>"New Hampshire NH"),
Array("id"=>"M:506","text"=>"---Boston MA-Manchester NH"),
Array("id"=>"US-NJ","text"=>"New Jersey NJ"),
Array("id"=>"US-NM","text"=>"New Mexico NM"),
Array("id"=>"M:790","text"=>"---Albuquerque-Santa Fe NM"),
Array("id"=>"M:532","text"=>"---Albany-Schenectady-Troy NY"),
Array("id"=>"M:502","text"=>"---Binghamton NY"),
Array("id"=>"M:514","text"=>"---Buffalo NY"),
Array("id"=>"M:523","text"=>"---Burlington VT-Plattsburgh NY"),
Array("id"=>"M:565","text"=>"---Elmira NY"),
Array("id"=>"M:501","text"=>"---New York NY"),
Array("id"=>"M:538","text"=>"---Rochester NY"),
Array("id"=>"M:555","text"=>"---Syracuse NY"),
Array("id"=>"M:526","text"=>"---Utica NY"),
Array("id"=>"M:549","text"=>"---Watertown NY"),
Array("id"=>"US-NC","text"=>"North Carolina NC"),
Array("id"=>"M:517","text"=>"---Charlotte NC"),
Array("id"=>"M:518","text"=>"---Greensboro-High Point-Winston Salem NC"),
Array("id"=>"M:545","text"=>"---Greenville-New Bern-Washington NC"),
Array("id"=>"M:567","text"=>"---Greenville-Spartanburg SC-Asheville NC-Anderson SC"),
Array("id"=>"M:560","text"=>"---Raleigh-Durham (Fayetteville) NC"),
Array("id"=>"M:550","text"=>"---Wilmington NC"),
Array("id"=>"US-ND","text"=>"North Dakota ND"),
Array("id"=>"M:724","text"=>"---Fargo-Valley City ND"),
Array("id"=>"M:687","text"=>"---Minot-Bismarck-Dickinson(Williston) ND"),
Array("id"=>"US-OH","text"=>"Ohio OH"),
Array("id"=>"M:515","text"=>"---Cincinnati OH"),
Array("id"=>"M:510","text"=>"---Cleveland-Akron (Canton) OH"),
Array("id"=>"M:535","text"=>"---Columbus OH"),
Array("id"=>"M:542","text"=>"---Dayton OH"),
Array("id"=>"M:558","text"=>"---Lima OH"),
Array("id"=>"M:547","text"=>"---Toledo OH"),
Array("id"=>"M:554","text"=>"---Wheeling WV-Steubenville OH"),
Array("id"=>"M:536","text"=>"---Youngstown OH"),
Array("id"=>"M:596","text"=>"---Zanesville OH"),
Array("id"=>"US-OK","text"=>"Oklahoma OK"),
Array("id"=>"M:650","text"=>"---Oklahoma City OK"),
Array("id"=>"M:657","text"=>"---Sherman TX-Ada OK"),
Array("id"=>"M:671","text"=>"---Tulsa OK"),
Array("id"=>"M:627","text"=>"---Wichita Falls TX &amp; Lawton OK"),
Array("id"=>"US-OR","text"=>"Oregon OR"),
Array("id"=>"M:821","text"=>"---Bend OR"),
Array("id"=>"M:801","text"=>"---Eugene OR"),
Array("id"=>"M:813","text"=>"---Medford-Klamath Falls OR"),
Array("id"=>"M:820","text"=>"---Portland OR"),
Array("id"=>"US-PA","text"=>"Pennsylvania PA"),
Array("id"=>"M:516","text"=>"---Erie PA"),
Array("id"=>"M:566","text"=>"---Harrisburg-Lancaster-Lebanon-York PA"),
Array("id"=>"M:574","text"=>"---Johnstown-Altoona PA"),
Array("id"=>"M:504","text"=>"---Philadelphia PA"),
Array("id"=>"M:508","text"=>"---Pittsburgh PA"),
Array("id"=>"M:577","text"=>"---Wilkes Barre-Scranton PA"),
Array("id"=>"US-RI","text"=>"Rhode Island RI"),
Array("id"=>"M:521","text"=>"---Providence RI-New Bedford MA"),
Array("id"=>"US-SC","text"=>"South Carolina SC"),
Array("id"=>"M:519","text"=>"---Charleston SC"),
Array("id"=>"M:546","text"=>"---Columbia SC"),
Array("id"=>"M:570","text"=>"---Florence-Myrtle Beach SC"),
Array("id"=>"M:567","text"=>"---Greenville-Spartanburg SC-Asheville NC-Anderson SC"),
Array("id"=>"US-SD","text"=>"South Dakota SD"),
Array("id"=>"M:764","text"=>"---Rapid City SD"),
Array("id"=>"M:725","text"=>"---Sioux Falls(Mitchell) SD"),
Array("id"=>"US-TN","text"=>"Tennessee TN"),
Array("id"=>"M:575","text"=>"---Chattanooga TN"),
Array("id"=>"M:718","text"=>"---Jackson TN"),
Array("id"=>"M:557","text"=>"---Knoxville TN"),
Array("id"=>"M:640","text"=>"---Memphis TN"),
Array("id"=>"M:659","text"=>"---Nashville TN"),
Array("id"=>"M:531","text"=>"---Tri-Cities TN-VA"),
Array("id"=>"US-TX","text"=>"Texas TX"),
Array("id"=>"M:662","text"=>"---Abilene-Sweetwater TX"),
Array("id"=>"M:634","text"=>"---Amarillo TX"),
Array("id"=>"M:635","text"=>"---Austin TX"),
Array("id"=>"M:692","text"=>"---Beaumont-Port Arthur TX"),
Array("id"=>"M:600","text"=>"---Corpus Christi TX"),
Array("id"=>"M:623","text"=>"---Dallas-Ft. Worth TX"),
Array("id"=>"M:765","text"=>"---El Paso TX"),
Array("id"=>"M:636","text"=>"---Harlingen-Weslaco-Brownsville-McAllen TX"),
Array("id"=>"M:618","text"=>"---Houston TX"),
Array("id"=>"M:749","text"=>"---Laredo TX"),
Array("id"=>"M:651","text"=>"---Lubbock TX"),
Array("id"=>"M:633","text"=>"---Odessa-Midland TX"),
Array("id"=>"M:661","text"=>"---San Angelo TX"),
Array("id"=>"M:641","text"=>"---San Antonio TX"),
Array("id"=>"M:657","text"=>"---Sherman TX-Ada OK"),
Array("id"=>"M:709","text"=>"---Tyler-Longview(Lufkin &amp; Nacogdoches) TX"),
Array("id"=>"M:626","text"=>"---Victoria TX"),
Array("id"=>"M:625","text"=>"---Waco-Temple-Bryan TX"),
Array("id"=>"M:627","text"=>"---Wichita Falls TX &amp; Lawton OK"),
Array("id"=>"US-UT","text"=>"Utah UT"),
Array("id"=>"M:770","text"=>"---Salt Lake City UT"),
Array("id"=>"US-VT","text"=>"Vermont VT"),
Array("id"=>"M:523","text"=>"---Burlington VT-Plattsburgh NY"),
Array("id"=>"US-VA","text"=>"Virginia VA"),
Array("id"=>"M:584","text"=>"---Charlottesville VA"),
Array("id"=>"M:569","text"=>"---Harrisonburg VA"),
Array("id"=>"M:544","text"=>"---Norfolk-Portsmouth-Newport News VA"),
Array("id"=>"M:556","text"=>"---Richmond-Petersburg VA"),
Array("id"=>"M:573","text"=>"---Roanoke-Lynchburg VA"),
Array("id"=>"M:531","text"=>"---Tri-Cities TN-VA"),
Array("id"=>"US-WA","text"=>"Washington WA"),
Array("id"=>"M:819","text"=>"---Seattle-Tacoma WA"),
Array("id"=>"M:881","text"=>"---Spokane WA"),
Array("id"=>"M:810","text"=>"---Yakima-Pasco-Richland-Kennewick WA"),
Array("id"=>"US-WV","text"=>"West Virginia WV"),
Array("id"=>"M:559","text"=>"---Bluefield-Beckley-Oak Hill WV"),
Array("id"=>"M:564","text"=>"---Charleston-Huntington WV"),
Array("id"=>"M:598","text"=>"---Clarksburg-Weston WV"),
Array("id"=>"M:597","text"=>"---Parkersburg WV"),
Array("id"=>"M:554","text"=>"---Wheeling WV-Steubenville OH"),
Array("id"=>"US-WI","text"=>"Wisconsin WI"),
Array("id"=>"M:676","text"=>"---Duluth MN-Superior WI"),
Array("id"=>"M:658","text"=>"---Green Bay-Appleton WI"),
Array("id"=>"M:702","text"=>"---La Crosse-Eau Claire WI"),
Array("id"=>"M:669","text"=>"---Madison WI"),
Array("id"=>"M:617","text"=>"---Milwaukee WI"),
Array("id"=>"M:705","text"=>"---Wausau-Rhinelander WI"),
Array("id"=>"US-WY","text"=>"Wyoming WY"),
Array("id"=>"M:767","text"=>"---Casper-Riverton WY"),
Array("id"=>"M:759","text"=>"---Cheyenne WY-Scottsbluff NE")),
'UG'=>Array(Array("id"=>"UG-XX","text"=>"Mumbo"),Array("id"=>"UG-YY","text"=>"Jumbo"))
),
'languages'=>Array(
Array("id"=>"*","text"=>"All Languages"),
Array("id"=>"","text"=>"------"),
Array("id"=>"en","text"=>"English"),
Array("id"=>"zh-CN","text"=>"Chinese (simplified)"),
Array("id"=>"zh-TW","text"=>"Chinese (traditional)"),
Array("id"=>"da","text"=>"Danish"),
Array("id"=>"nl","text"=>"Dutch"),
Array("id"=>"fi","text"=>"Finnish"),
Array("id"=>"fr","text"=>"French"),
Array("id"=>"de","text"=>"German"),
Array("id"=>"iw","text"=>"Hebrew"),
Array("id"=>"it","text"=>"Italian"),
Array("id"=>"ja","text"=>"Japanese"),
Array("id"=>"ko","text"=>"Korean"),
Array("id"=>"no","text"=>"Norwegian"),
Array("id"=>"pl","text"=>"Polish"),
Array("id"=>"ru","text"=>"Russian"),
Array("id"=>"es","text"=>"Spanish"),
Array("id"=>"sv","text"=>"Swedish"),
Array("id"=>"tr","text"=>"Turkish"),
Array("id"=>"","text"=>"------"),
Array("id"=>"ar","text"=>"Arabic"),
Array("id"=>"bg","text"=>"Bulgarian"),
Array("id"=>"ca","text"=>"Catalan"),
Array("id"=>"zh-CN","text"=>"Chinese (simplified)"),
Array("id"=>"zh-TW","text"=>"Chinese (traditional)"),
Array("id"=>"hr","text"=>"Croatian"),
Array("id"=>"cs","text"=>"Czech"),
Array("id"=>"da","text"=>"Danish"),
Array("id"=>"nl","text"=>"Dutch"),
Array("id"=>"en","text"=>"English"),
Array("id"=>"et","text"=>"Estonian"),
Array("id"=>"fi","text"=>"Finnish"),
Array("id"=>"fr","text"=>"French"),
Array("id"=>"de","text"=>"German"),
Array("id"=>"el","text"=>"Greek"),
Array("id"=>"iw","text"=>"Hebrew"),
Array("id"=>"hi","text"=>"Hindi"),
Array("id"=>"hu","text"=>"Hungarian"),
Array("id"=>"is","text"=>"Icelandic"),
Array("id"=>"id","text"=>"Indonesian"),
Array("id"=>"it","text"=>"Italian"),
Array("id"=>"ja","text"=>"Japanese"),
Array("id"=>"ko","text"=>"Korean"),
Array("id"=>"lv","text"=>"Latvian"),
Array("id"=>"lt","text"=>"Lithuanian"),
Array("id"=>"no","text"=>"Norwegian"),
Array("id"=>"pl","text"=>"Polish"),
Array("id"=>"pt","text"=>"Portuguese"),
Array("id"=>"ro","text"=>"Romanian"),
Array("id"=>"ru","text"=>"Russian"),
Array("id"=>"sr","text"=>"Serbian"),
Array("id"=>"sk","text"=>"Slovak"),
Array("id"=>"sl","text"=>"Slovenian"),
Array("id"=>"es","text"=>"Spanish"),
Array("id"=>"sv","text"=>"Swedish"),
Array("id"=>"tl","text"=>"Tagalog"),
Array("id"=>"th","text"=>"Thai"),
Array("id"=>"tr","text"=>"Turkish"),
Array("id"=>"uk","text"=>"Ukrainian"),
Array("id"=>"ur","text"=>"Urdu"),
Array("id"=>"vi","text"=>"Vietnamese")),
'network'=>Array(
Array("id"=>"GoogleSearch","text"=>"Google Search"),
Array("id"=>"SearchNetwork","text"=>"Search Network"),
Array("id"=>"ContentNetwork","text"=>"Content Network"))
);
?>